# Generated by Django 5.1.3 on 2024-11-24 22:07

import employers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[employers.validators.validate_name])),
                ('birth_date', models.DateField(validators=[employers.validators.validate_birth_date])),
                ('department', models.CharField(blank=True, choices=[('HR', 'Human Resources'), ('DEV', 'Developers'), ('S&M', 'Sales&Marketing')], default=None, max_length=50, null=True)),
            ],
        ),
    ]
